/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MarketplaceDimensions } from "./marketplacedimensions";
import { Expose, Transform } from "class-transformer";

export class AWSMarketplaceMetadata extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "awsMarketplaceCustomerId" })
    awsMarketplaceCustomerId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "awsMarketplaceProductCode" })
    awsMarketplaceProductCode: string;

    @SpeakeasyMetadata()
    @Expose({ name: "createdBy" })
    createdBy?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "dimension" })
    dimension: MarketplaceDimensions;

    @SpeakeasyMetadata()
    @Expose({ name: "expirationTime" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    expirationTime: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "expirationUpdateTime" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    expirationUpdateTime: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "orgId" })
    orgId: string;
}
