/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LogSessionReferenceResponse } from "./logsessionreferenceresponse";
import { Expose, Type } from "class-transformer";

/**
 * Response payload for uploading reference profile.
 */
export class BatchLogSessionReferenceResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "observatoryUrl" })
    observatoryUrl?: string;

    @SpeakeasyMetadata({ elemType: LogSessionReferenceResponse })
    @Expose({ name: "references" })
    @Type(() => LogSessionReferenceResponse)
    references?: LogSessionReferenceResponse[];
}
