/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LogReferenceRequest } from "./logreferencerequest";
import { Expose, Type } from "class-transformer";

export class BatchLogReferenceRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: LogReferenceRequest })
    @Expose({ name: "references" })
    @Type(() => LogReferenceRequest)
    references?: LogReferenceRequest[];
}
