/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Column schema for a given column
 */
export class ColumnSchema extends SpeakeasyBase {
    /**
     * We can classify these columns into various grouping. Currently we only support 'input' and 'output'
     */
    @SpeakeasyMetadata()
    @Expose({ name: "classifier" })
    classifier: string;

    /**
     * The data type of the columns. Setting this field affects the default grouping (i.e integral columns)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "dataType" })
    dataType: string;

    /**
     * Whether a column should be discrete or continuous. Changing this column will change the default grouping (discrete columns vs. continuous columns
     */
    @SpeakeasyMetadata()
    @Expose({ name: "discreteness" })
    discreteness: string;
}
