/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Segment } from "./segment";
import { Expose, Type } from "class-transformer";

/**
 * Request payload for CreateReferenceProfile.
 */
export class CreateReferenceProfileRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "alias" })
    alias?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "datasetTimestamp" })
    datasetTimestamp?: number;

    @SpeakeasyMetadata({ elemType: Segment })
    @Expose({ name: "segments" })
    @Type(() => Segment)
    segments?: Segment[];

    @SpeakeasyMetadata()
    @Expose({ name: "tags" })
    tags?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}
