/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Request for creating a new user
 */
export class CreateUserRequest extends SpeakeasyBase {
    /**
     * The users email address
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;
}
