/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Response for creating sessions
 */
export class CreateSessionResponse extends SpeakeasyBase {
    /**
     * Token for the created session, to be passsed into other session APIs.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;
}
