/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Response payload for creating a reference profile.
 */
export class CreateReferenceProfileResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "alias" })
    alias?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "datasetId" })
    datasetId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "segments" })
    segments?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "uploadTimestamp" })
    uploadTimestamp?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "uploadUrls" })
    uploadUrls?: string[];
}
