/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class DatabricksConnection extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "accessToken" })
    accessToken: string;

    @SpeakeasyMetadata()
    @Expose({ name: "connected" })
    connected: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "createdBy" })
    createdBy: string;

    @SpeakeasyMetadata()
    @Expose({ name: "demo" })
    demo: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "hostname" })
    hostname: string;

    @SpeakeasyMetadata()
    @Expose({ name: "jobId" })
    jobId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "orgId" })
    orgId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "workspaceId" })
    workspaceId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "workspaceUrl" })
    workspaceUrl: string;
}
