/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DTOClustersAwsAvailabilityDTO } from "./dtoclustersawsavailabilitydto";
import { DTOEbsVolumeTypeDTO } from "./dtoebsvolumetypedto";
import { Expose } from "class-transformer";

export class DTOClustersAwsAttributesDTO extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "availability" })
    availability?: DTOClustersAwsAvailabilityDTO;

    @SpeakeasyMetadata()
    @Expose({ name: "ebsVolumeCount" })
    ebsVolumeCount?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "ebsVolumeSize" })
    ebsVolumeSize?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "ebsVolumeType" })
    ebsVolumeType?: DTOEbsVolumeTypeDTO;

    @SpeakeasyMetadata()
    @Expose({ name: "firstOnDemand" })
    firstOnDemand?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "instanceProfileArn" })
    instanceProfileArn?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "spotBidPricePercent" })
    spotBidPricePercent?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "zoneId" })
    zoneId?: string;
}
