/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum DTOClustersAwsAvailabilityDTO {
    Spot = "SPOT",
    OnDemand = "ON_DEMAND",
    SpotWithFallback = "SPOT_WITH_FALLBACK",
}
