/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum DTOEbsVolumeTypeDTO {
    GeneralPurposeSsd = "GENERAL_PURPOSE_SSD",
    ThroughputOptimizedHdd = "THROUGHPUT_OPTIMIZED_HDD",
}
