/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class DTOJobsNotebookTaskDTO extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "baseParameters" })
    baseParameters?: Record<string, string>;

    @SpeakeasyMetadata()
    @Expose({ name: "notebookPath" })
    notebookPath?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "revisionTimestamp" })
    revisionTimestamp?: number;
}
