/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class DTOJobsSparkPythonTaskDTO extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "parameters" })
    parameters?: Record<string, any>[];

    @SpeakeasyMetadata()
    @Expose({ name: "pythonFile" })
    pythonFile?: string;
}
