/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum DTOJobsDataSecurityModeDTO {
    SingleUser = "SINGLE_USER",
    UserIsolation = "USER_ISOLATION",
    LegacyPassthrough = "LEGACY_PASSTHROUGH",
    LegacyTableAcl = "LEGACY_TABLE_ACL",
}
