/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Response for getting dataset metadata
 */
export class GetDatasetMetadataResponse extends SpeakeasyBase {
    /**
     * Metadata information for the dataset
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    metadata: string;
}
