/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Membership } from "./membership";
import { Expose, Type } from "class-transformer";

/**
 * GetDefaultMembershipForEmail default response
 */
export class GetDefaultMembershipResponse extends SpeakeasyBase {
    /**
     * Response for the get memberships
     */
    @SpeakeasyMetadata()
    @Expose({ name: "membership" })
    @Type(() => Membership)
    membership?: Membership;
}
