/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AWSMarketplaceMetadata } from "./awsmarketplacemetadata";
import { Expose, Type } from "class-transformer";

/**
 * Response for listing organization
 */
export class GetMarketplaceMetadataResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => AWSMarketplaceMetadata)
    metadata: AWSMarketplaceMetadata;
}
