/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SessionMetadata } from "./sessionmetadata";
import { Expose, Type } from "class-transformer";

/**
 * Response for getting sessions.
 */
export class GetSessionResponse extends SpeakeasyBase {
    /**
     * Response for getting sessions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "session" })
    @Type(() => SessionMetadata)
    session: SessionMetadata;
}
