/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Membership } from "./membership";
import { Expose, Type } from "class-transformer";

/**
 * Response for the ListOrganizationMemberships API
 */
export class ListOrganizationMembershipsResponse extends SpeakeasyBase {
    /**
     * A list of all memberships in an organization.
     */
    @SpeakeasyMetadata({ elemType: Membership })
    @Expose({ name: "memberships" })
    @Type(() => Membership)
    memberships: Membership[];
}
