/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OrganizationSummary } from "./organizationsummary";
import { Expose, Type } from "class-transformer";

/**
 * Response for listing organization
 */
export class ListOrganizationsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "internal" })
    internal?: boolean;

    /**
     * A list of all known organization metadata
     */
    @SpeakeasyMetadata({ elemType: OrganizationSummary })
    @Expose({ name: "items" })
    @Type(() => OrganizationSummary)
    items: OrganizationSummary[];
}
