/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { UserApiKey } from "./userapikey";
import { Expose, Type } from "class-transformer";

/**
 * Response for listing API key metadata
 */
export class ListUserApiKeys extends SpeakeasyBase {
    /**
     * A list of all known API key metadata
     */
    @SpeakeasyMetadata({ elemType: UserApiKey })
    @Expose({ name: "items" })
    @Type(() => UserApiKey)
    items: UserApiKey[];
}
