/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Response payload for uploading reference profile.
 */
export class LogReferenceResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "alias" })
    alias?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "modelId" })
    modelId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "uploadTimestamp" })
    uploadTimestamp?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "uploadUrl" })
    uploadUrl?: string;
}
