/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Request payload for LogReference.
 */
export class LogReferenceRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "alias" })
    alias?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "datasetTimestamp" })
    datasetTimestamp?: number;
}
