/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum MarketplaceDimensions {
    Free = "FREE",
    Models2 = "MODELS_2",
    Models3 = "MODELS_3",
    Models4 = "MODELS_4",
    Models5 = "MODELS_5",
    ByQuantity = "BY_QUANTITY",
    Enterprise = "ENTERPRISE",
}
