/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Role } from "./role";
import { Expose } from "class-transformer";

/**
 * CreateMembership default response
 */
export class MembershipMetadata extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "default" })
    default?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "orgId" })
    orgId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "role" })
    role?: Role;

    @SpeakeasyMetadata()
    @Expose({ name: "userId" })
    userId?: string;
}
