/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Response for the model metadata
 */
export class ModelMetadataResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "active" })
    active?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "creationTime" })
    creationTime?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    @SpeakeasyMetadata()
    @Expose({ name: "modelCategory" })
    modelCategory?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "modelType" })
    modelType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "orgId" })
    orgId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "timePeriod" })
    timePeriod?: string;
}
