/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The [ModelType] of the dataset
 */
export enum ModelType {
    Classification = "CLASSIFICATION",
    Regression = "REGRESSION",
    Embeddings = "EMBEDDINGS",
    Llm = "LLM",
    Ranking = "RANKING",
    ModelOther = "MODEL_OTHER",
    DataSource = "DATA_SOURCE",
    DataStream = "DATA_STREAM",
    DataTransform = "DATA_TRANSFORM",
    DataOther = "DATA_OTHER",
}
