/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class MonitorConfigVersion extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "lastModified" })
    lastModified?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "path" })
    path?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "versionId" })
    versionId?: string;
}
