/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum NotificationSqsMessageCadence {
    Hourly = "HOURLY",
    Daily = "DAILY",
    Weekly = "WEEKLY",
    Individual = "INDIVIDUAL",
}
