/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Pager Duty payload for Notification Actions
 */
export class PagerDutyNotificationAction extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "pagerDutyKey" })
    pagerDutyKey: string;
}
