/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * ProvisionAWSMarketplaceNewUser default response
 */
export class ProvisionNewAWSMarketplaceUserResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "customerId" })
    customerId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "modelId" })
    modelId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "orgId" })
    orgId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "userId" })
    userId: string;
}
