/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A single reference item response.
 */
export class ReferenceProfileItemResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "alias" })
    alias?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "datasetTimestamp" })
    datasetTimestamp?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "downloadUrl" })
    downloadUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "downloadUrls" })
    downloadUrls?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "modelId" })
    modelId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "orgId" })
    orgId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "segments" })
    segments?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "uploadTimestamp" })
    uploadTimestamp?: number;
}
