/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DatabricksConnection } from "./databricksconnection";
import { Expose, Type } from "class-transformer";

/**
 * RefreshConnection default response
 */
export class RefreshConnectionByOrgIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => DatabricksConnection)
    connection: DatabricksConnection;
}
