/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class RegisterDatabricksConnectionRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "accessToken" })
    accessToken: string;

    @SpeakeasyMetadata()
    @Expose({ name: "cloudProvider" })
    cloudProvider: string;

    @SpeakeasyMetadata()
    @Expose({ name: "connectionEstablished" })
    connectionEstablished?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "connectionId" })
    connectionId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "demo" })
    demo: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;

    @SpeakeasyMetadata()
    @Expose({ name: "freeTrial" })
    freeTrial?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "hostname" })
    hostname: string;

    @SpeakeasyMetadata()
    @Expose({ name: "port" })
    port: number;

    @SpeakeasyMetadata()
    @Expose({ name: "workspaceId" })
    workspaceId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "workspaceUrl" })
    workspaceUrl: string;
}
