/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * UpdateConnection default response
 */
export class Response extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "requestId" })
    requestId?: string;
}
