/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * RunJob default response
 */
export class RunJobResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "runId" })
    runId: number;
}
