/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SearchIndexType } from "./searchindextype";
import { Expose } from "class-transformer";

export class SearchIndexRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "orgId" })
    orgId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: SearchIndexType;
}
