/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum SearchIndexType {
    Models = "MODELS",
    Actions = "ACTIONS",
    EntitySchema = "ENTITY_SCHEMA",
    MonitorConfig = "MONITOR_CONFIG",
}
