/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EntitySearchResult } from "./entitysearchresult";
import { Expose, Type } from "class-transformer";

/**
 * WhyLabs Search default response
 */
export class SearchResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "requestId" })
    requestId?: string;

    @SpeakeasyMetadata({ elemType: EntitySearchResult })
    @Expose({ name: "results" })
    @Type(() => EntitySearchResult)
    results?: EntitySearchResult[];
}
