/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Segment } from "./segment";
import { Expose, Type } from "class-transformer";

/**
 * A segment list response.
 */
export class SegmentListResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "modelId" })
    modelId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "orgId" })
    orgId?: string;

    @SpeakeasyMetadata({ elemType: Segment })
    @Expose({ name: "segments" })
    @Type(() => Segment)
    segments?: Segment[];
}
