/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SegmentTag } from "./segmenttag";
import { Expose, Type } from "class-transformer";

export class Segment extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: SegmentTag })
    @Expose({ name: "tags" })
    @Type(() => SegmentTag)
    tags?: SegmentTag[];
}
