/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Response for getting sessions.
 */
export class SessionMetadata extends SpeakeasyBase {
    /**
     * The model id of the session. There should only be a single model.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "modelId" })
    modelId?: string;

    /**
     * The org id of the session
     */
    @SpeakeasyMetadata()
    @Expose({ name: "orgId" })
    orgId?: string;

    /**
     * The id of the session
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sessionId" })
    sessionId?: string;

    /**
     * The generated user id for the session.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "userId" })
    userId?: string;
}
