/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Slack payload for Notification Actions
 */
export class SlackNotificationAction extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "slackWebhook" })
    slackWebhook: string;
}
