/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Organization's subscription tier. Should be PAID for real customers
 */
export enum SubscriptionTier {
    Free = "FREE",
    Paid = "PAID",
    AwsMarketplace = "AWS_MARKETPLACE",
    Subscription = "SUBSCRIPTION",
}
