/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The [TimePeriod] for data aggregation/alerting for a model
 */
export enum TimePeriod {
    P1M = "P1M",
    P1W = "P1W",
    P1D = "P1D",
    Pt1H = "PT1H",
}
