/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { NotificationSettingsDay } from "./notificationsettingsday";
import { NotificationSqsMessageCadence } from "./notificationsqsmessagecadence";
import { Expose } from "class-transformer";

/**
 *
 * @remarks
 * Combination of all possible schedule types, a hacky workaround for bugs in generated clients that use polymorphic types.
 * There are three types of schedules. Weekly, Daily, and Individual. You need to set the right fields for each one.
 *
 * Weekly:
 *     enabled, cadence=WEEKLY, dayOfWeek, local24HourOfDay, localMinuteOfHour, localTimezone
 *
 * Daily:
 *     enabled, cadence=DAILY, local24HourOfDay, localMinuteOfHour, localTimezone
 *
 * Individual:
 *     enabled, cadence=INDIVIDUAL
 *
 */
export class UberNotificationSchedule extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "cadence" })
    cadence: NotificationSqsMessageCadence;

    @SpeakeasyMetadata()
    @Expose({ name: "dayOfWeek" })
    dayOfWeek?: NotificationSettingsDay;

    @SpeakeasyMetadata()
    @Expose({ name: "enabled" })
    enabled: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "local24HourOfDay" })
    local24HourOfDay?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "localMinuteOfHour" })
    localMinuteOfHour?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "localTimezone" })
    localTimezone?: string;
}
