/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { UpdateConnectionChanges } from "./updateconnectionchanges";
import { Expose, Type } from "class-transformer";

export class UpdateConnectionRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "changes" })
    @Type(() => UpdateConnectionChanges)
    changes?: UpdateConnectionChanges;

    @SpeakeasyMetadata()
    @Expose({ name: "orgId" })
    orgId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "workspaceId" })
    workspaceId?: string;
}
