/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class UpdateConnectionChanges extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "connected" })
    connected?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "demo" })
    demo?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "orgId" })
    orgId?: string;
}
