/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * User metadata
 */
export class User extends SpeakeasyBase {
    /**
     * The user's email address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;

    /**
     * The user's JSON serialized preferences. Schema defined in Dashbird.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "preferences" })
    preferences?: string;

    /**
     * The id of the user.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "userId" })
    userId: string;
}
