/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class BatchCreateReferenceProfileUploadRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    batchLogReferenceRequest: shared.BatchLogReferenceRequest;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=session_id" })
    sessionId: string;
}

export class BatchCreateReferenceProfileUploadResponse extends SpeakeasyBase {
    /**
     * BatchCreateReferenceProfileUpload default response
     */
    @SpeakeasyMetadata()
    batchLogSessionReferenceResponse?: shared.BatchLogSessionReferenceResponse;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
