/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class PutRequestMonitorRunConfigSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=apiKey;subtype=header;name=X-API-Key" })
    apiKeyAuth: string;
}

export class PutRequestMonitorRunConfigRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "analyzer_ids" })
    analyzerIds?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "end_timestamp" })
    endTimestamp?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "overwrite" })
    overwrite?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "start_timestamp" })
    startTimestamp?: number;
}

export class PutRequestMonitorRunConfigRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody: PutRequestMonitorRunConfigRequestBody;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=dataset_id" })
    datasetId: string;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=org_id" })
    orgId: string;
}

export class PutRequestMonitorRunConfigResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * PutRequestMonitorRunConfig default response
     */
    @SpeakeasyMetadata()
    putRequestMonitorRunConfigDefaultApplicationJSONString?: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
