/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class RevokeApiKeySecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=apiKey;subtype=header;name=X-API-Key" })
    apiKeyAuth: string;
}

export class RevokeApiKeyRequest extends SpeakeasyBase {
    /**
     * ID of the key to revoke
     *
     * @remarks
     *  Metadata for the revoked API Key
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=key_id" })
    keyId: string;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=org_id" })
    orgId: string;

    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=user_id" })
    userId: string;
}

export class RevokeApiKeyResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Revoked API Key's metadata
     */
    @SpeakeasyMetadata()
    userApiKey?: shared.UserApiKey;
}
