/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as utils from "../internal/utils";
import * as operations from "./models/operations";
import { SDKConfiguration } from "./sdk";
import { AxiosInstance, AxiosRequestConfig, AxiosResponse } from "axios";

export class Schema {
    private sdkConfiguration: SDKConfiguration;

    constructor(sdkConfig: SDKConfiguration) {
        this.sdkConfiguration = sdkConfig;
    }

    /**
     * Get the current supported schema of the monitor configuration
     *
     * @remarks
     * Get the current supported schema of the  monitor configuration
     */
    async getMonitorConfigSchema(
        req: operations.GetMonitorConfigSchemaRequest,
        security: operations.GetMonitorConfigSchemaSecurity,
        config?: AxiosRequestConfig
    ): Promise<operations.GetMonitorConfigSchemaResponse> {
        if (!(req instanceof utils.SpeakeasyBase)) {
            req = new operations.GetMonitorConfigSchemaRequest(req);
        }

        const baseURL: string = utils.templateUrl(
            this.sdkConfiguration.serverURL,
            this.sdkConfiguration.serverDefaults
        );
        const url: string = utils.generateURL(
            baseURL,
            "/v0/organizations/{org_id}/schema/monitor-config",
            req
        );

        if (!(security instanceof utils.SpeakeasyBase)) {
            security = new operations.GetMonitorConfigSchemaSecurity(security);
        }
        const client: AxiosInstance = utils.createSecurityClient(
            this.sdkConfiguration.defaultClient,
            security
        );

        const headers = { ...config?.headers };
        headers["Accept"] = "application/json";
        headers[
            "user-agent"
        ] = `speakeasy-sdk/${this.sdkConfiguration.language} ${this.sdkConfiguration.sdkVersion} ${this.sdkConfiguration.genVersion}`;

        const httpRes: AxiosResponse = await client.request({
            validateStatus: () => true,
            url: url,
            method: "get",
            headers: headers,
            ...config,
        });

        const contentType: string = httpRes?.headers?.["content-type"] ?? "";

        if (httpRes?.status == null) {
            throw new Error(`status code not found in response: ${httpRes}`);
        }

        const res: operations.GetMonitorConfigSchemaResponse =
            new operations.GetMonitorConfigSchemaResponse({
                statusCode: httpRes.status,
                contentType: contentType,
                rawResponse: httpRes,
            });
        switch (true) {
            default:
                if (utils.matchContentType(contentType, `application/json`)) {
                    res.getMonitorConfigSchemaDefaultApplicationJSONString = JSON.stringify(
                        httpRes?.data
                    );
                }
                break;
        }

        return res;
    }
}
